export const bookingInformationOptions = [
  "B/L No.",
  "Container No.",
  "SCAC Code",
  "Container Type/Size",
  "Customer Reference No.",
  "Seal No.",
  "Purchase Order No.",
  "Export Reference No.",
  "Invoice No.",
  "IT No.",
  "Shipper Name",
  "Forwarder Name",
  "Consignee Name",
  "Notify Party Name",
  "Also Notify Name",
  "Receive Term/Delivery Term",
  "Commodity",
  "Total Package",
  "Total Weight",
  "Total Measure",
  "MRN (E.U Destined Only)",
  "Firms Code",
  "House B/L Check",
  "Issue Date",
  "VGM",
  "Surrender Date",
  "VGM Unit",
  "On-Board Date",
  "VGM Submission Date(LT)",
  "VVD",
];

export const routeInformationOptions = [
  "Current Status",
  "Service Lane",
  "Pre-Carrier",
  "Trunk Vessel",
  "Post Carrier",
  "Place of Receipt",
  "Port of Loading",
  "Port of Discharging",
  "Place of Delivery",
  "CY in Date",
  "Loading Date at Port of Loading",
  "Departure Date from Port of Loading",
  "Arrival Date at Port of Discharging",
  "Unloading Date at Port of Discharging",
  "Inbound CY",
  "Pick-Up Date",
  "Truck Gate Out from I/B Terminal",
  "Total Transit Time(Estimated)",
  "Total Transit Time(Actual)",
  "Delivery ETA",
];

export const chargeInformationOptions = ["Prepaid Charge", "Collect Charge"];

export const inboundInformationOptions = ["Customs Clearance"];
